//! OpenAI API client generated by [o3gen](https://github.com/dineshdb/o3gen).
//!
//! Provides typed request/response structs and an [`OpenAIApi`] trait with a
//! default [`OpenAIApiClient`] implementation backed by `reqwest`.
//!
//! # Quick start
//!
//! ```no_run
//! use o3gen_openai::{OpenAIApi, OpenAIApiClient};
//! use o3gen_openai::types::*;
//!
//! # #[tokio::main]
//! # async fn main() -> Result<(), o3gen_openai::ApiError> {
//! let client = OpenAIApiClient::new("https://api.openai.com/v1".into());
//!
//! let body = CreateChatCompletionRequest::builder()
//!     .model(CreateChatCompletionRequestModel::String("gpt-4o".into()))
//!     .messages(vec![ChatCompletionRequestMessage::UserMessage(
//!         ChatCompletionRequestUserMessage::builder()
//!             .role(ChatCompletionRequestUserMessageRole::User)
//!             .content(ChatCompletionRequestUserMessageContent::String(
//!                 "Hello!".into(),
//!             ))
//!             .build()?,
//!     )])
//!     .build()?;
//!
//! let resp = OpenAIApi::create_chat_completion(&client, body).await?;
//! println!("{}", resp.choices[0].message.content.as_deref().unwrap_or_default());
//! # Ok(())
//! # }
//! ```

include!(concat!(env!("OUT_DIR"), "/openai.rs"));

#[cfg(test)]
pub mod tests;
